/** Демо-правила для SEED_DEMO=true: по одному-два на тему, чтобы интерфейс не был пустым. */
import type { Enrichment } from '../types.js';

export type Demo = Omit<
  Enrichment,
  'kind' | 'language' | 'strength' | 'why' | 'example_good' | 'example_bad'
> &
  Partial<Pick<Enrichment, 'why' | 'example_good' | 'example_bad'>>;

export const DEMO: Demo[] = [
  {
    folder_path: ['ChatGPT', 'Не люблю'],
    statement: 'Длинные вступления перед ответом',
    details: 'Сразу к сути, без пересказа вопроса.',
    polarity: 'dislike',
    domain: 'ai_assistants',
    project: null,
    applies_to: ['chatgpt'],
    tags: ['ответы', 'краткость', 'стиль'],
    constraints: [],
    level: 'hard',
  },
  {
    folder_path: ['ChatGPT', 'Люблю'],
    statement: 'Ответы списком с конкретными шагами',
    details: null,
    polarity: 'like',
    domain: 'ai_assistants',
    project: null,
    applies_to: ['chatgpt'],
    tags: ['ответы', 'структура', 'шаги'],
    constraints: [],
    level: 'default',
  },
  {
    folder_path: ['Программирование', 'Код', 'Не люблю'],
    statement: 'Функции длиннее 40 строк',
    details: null,
    polarity: 'dislike',
    domain: 'programming',
    project: null,
    applies_to: ['any_ai'],
    tags: ['код', 'функции', 'размер'],
    constraints: [{ metric: 'function_lines', operator: '<=', value: 40, unit: 'lines' }],
    level: 'hard',
    why: 'Длинную функцию трудно прочитать и проверить целиком.',
    example_good: 'Шаги по функциям: parse(), validate(), save()',
    example_bad: 'Одна функция на 120 строк',
  },
  {
    folder_path: ['Программирование', 'Код', 'Люблю'],
    statement: 'Понятные имена переменных',
    details: null,
    polarity: 'like',
    domain: 'programming',
    project: null,
    applies_to: ['any_ai'],
    tags: ['код', 'имена', 'читаемость'],
    constraints: [],
    level: 'default',
  },
  {
    folder_path: ['Программирование', 'PHP', 'Люблю'],
    statement: 'Строгая типизация в PHP',
    details: 'declare(strict_types=1) в каждом файле.',
    polarity: 'like',
    domain: 'programming',
    project: null,
    applies_to: ['php'],
    tags: ['php', 'типы', 'строгость'],
    constraints: [],
    level: 'hard',
  },
  {
    folder_path: ['Программирование', 'PHP', 'Не люблю'],
    statement: 'Глобальные переменные в PHP',
    details: null,
    polarity: 'dislike',
    domain: 'programming',
    project: null,
    applies_to: ['php'],
    tags: ['php', 'глобальные', 'архитектура'],
    constraints: [],
    level: 'default',
  },
  {
    folder_path: ['Рыбалка', 'Люблю'],
    statement: 'Рыбалка на рассвете у тихой воды',
    details: null,
    polarity: 'like',
    domain: 'fishing',
    project: null,
    applies_to: ['me'],
    tags: ['рыбалка', 'рассвет', 'тишина'],
    constraints: [],
    level: 'hard',
  },
  {
    folder_path: ['Рыбалка', 'Не люблю'],
    statement: 'Шумные соседи на берегу',
    details: null,
    polarity: 'dislike',
    domain: 'fishing',
    project: null,
    applies_to: ['me'],
    tags: ['рыбалка', 'шум', 'берег'],
    constraints: [],
    level: 'default',
  },
  {
    folder_path: ['Проекты', 'Семейный чат', 'Люблю'],
    statement: 'Минимальный UI',
    details: null,
    polarity: 'like',
    domain: 'project',
    project: 'Семейный чат',
    applies_to: ['any_ai'],
    tags: ['интерфейс', 'минимализм', 'дизайн'],
    constraints: [],
    level: 'hard',
  },
  {
    folder_path: ['Проекты', 'Семейный чат', 'Не люблю'],
    statement: 'Лишние уведомления',
    details: null,
    polarity: 'dislike',
    domain: 'project',
    project: 'Семейный чат',
    applies_to: ['any_ai'],
    tags: ['уведомления', 'шум', 'интерфейс'],
    constraints: [],
    level: 'default',
  },
];
